package(default_visibility = ["//visibility:public"])

cc_library(
    name = "glfw",
    hdrs = glob([
        "src/internal.h",
        "src/mappings.h",
        "include/GLFW/glfw3.h",
        "include/GLFW/glfw3native.h",
        "src/x11_platform.h",
        "src/xkb_unicode.h",
        "src/posix_time.h",
        "src/posix_thread.h",
        "src/glx_context.h",
        "src/egl_context.h",
        "src/osmesa_context.h",
        "src/linux_joystick.h",
    ]),
    srcs = glob([
        "src/init.c",
        "src/input.c",
        "src/window.c",
        "src/monitor.c",
        "src/context.c",
        "src/vulkan.c",
        "src/posix_thread.c",
        "src/x11_init.c",
        "src/x11_monitor.c",
        "src/x11_window.c",
        "src/xkb_unicode.c",
        "src/posix_time.c",
        "src/posix_thread.c",
        "src/glx_context.c",
        "src/egl_context.c",
        "src/osmesa_context.c",
        "src/linux_joystick.c",
    ]),
    includes = ["include"],
    copts = ["-D_GLFW_X11"],
    linkopts  = ["-lX11", "-lGL", "-lpthread", "-ldl"],
    linkstatic = False,
)
